### ISSUE TITLE
 No such file or directory: 'experiments/test_clsI_6kzw/test_clsI_6kzw_pmhc_oc/model_scores.txt'

### ISSUE THREAD

**Issue by ddiem-ri-4D** [piercelab/tcrmodel2#23] opened 2024-08-17 12:40 UTC
Hi @bpierce12 @rui-yin @shayanask @piercelab

I'm encountering the following error after running the command:

python run_tcrmodel2.py \
--job_id=test_clsI_6kzw \
--output_dir=experiments/ \
--tcra_seq=AQEVTQIPAALSVPEGENLVLNCSFTDSAIYNLQWFRQDPGKGLTSLLLIQSSQREQTSGRLNASLDKSSGRSTLYIAASQPGDSATYLCAVTNQAGTALIFGKGTTLSVSS \
--tcrb_seq=NAGVTQTPKFQVLKTGQSMTLQCSQDMNHEYMSWYRQDPGMGLRLIHYSVGAGITDQGEVPNGYNVSRSTTEDFPLRLLSAAPSQTSVYFCASSYSIRGSRGEQFFGPGTRLTVL \
--pep_seq=RLPAKAPLL \
--mhca_seq=SHSLKYFHTSVSRPGRGEPRFISVGYVDDTQFVRFDNDAASPRMVPRAPWMEQEGSEYWDRETRSARDTAQIFRVNLRTLRGYYNQSEAGSHTLQWMHGCELGPDGRFLRGYEQFAYDGKDYLTLNEDLRSWTAVDTAAQISEQKSNDASEAEHQRAYLEDTCVEWLHKYLEKGKETLLH \ 
--ori_db=/mnt/DATAR09/DATA_DIEM/DATASM02/DATATCRTOOLS/tcrmodel2/data/databases

Do you know what issue I might be facing, and could you help me fix it?
Thank you very much.

My Diem

Traceback (most recent call last):
  File "run_alphafold_tcrmodel2.3.py", line 41, in <module>
    from alphafold.model import data
  File "/mnt/DATAR09/DATA_DIEM/DATASM02/DATATCRTOOLS/tcrmodel2/alphafold/model/data.py", line 19, in <module>
    from alphafold.model import utils
  File "/mnt/DATAR09/DATA_DIEM/DATASM02/DATATCRTOOLS/tcrmodel2/alphafold/model/utils.py", line 23, in <module>
    import haiku as hk
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/__init__.py", line 19, in <module>
    from haiku import data_structures
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_haiku_dict
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/_src/utils.py", line 42, in <module>
    def auto_repr(cls: type[Any], *args, **kwargs) -> str:
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "run_alphafold_tcrmodel2.3.py", line 41, in <module>
    from alphafold.model import data
  File "/mnt/DATAR09/DATA_DIEM/DATASM02/DATATCRTOOLS/tcrmodel2/alphafold/model/data.py", line 19, in <module>
    from alphafold.model import utils
  File "/mnt/DATAR09/DATA_DIEM/DATASM02/DATATCRTOOLS/tcrmodel2/alphafold/model/utils.py", line 23, in <module>
    import haiku as hk
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/__init__.py", line 19, in <module>
    from haiku import data_structures
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_haiku_dict
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/haiku/_src/utils.py", line 42, in <module>
    def auto_repr(cls: type[Any], *args, **kwargs) -> str:
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "run_tcrmodel2.py", line 408, in <module>
    app.run(main)
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/diem/anaconda3/envs/tcrmodel/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_tcrmodel2.py", line 238, in main
    with open("%s/%s_pmhc_oc/model_scores.txt" % (out_dir, job_id)) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/test_clsI_6kzw/test_clsI_6kzw_pmhc_oc/model_scores.txt'

**Comment by bpierce12** [comment] 2024-08-21 18:13
Hi My Diem,

Thank you for checking on that. It seems that the initial TypeError error
is leading to a failed execution and the later error where model_scores.txt
is not found. We tried to reproduce your error with the same inputs here
with TCRmodel2, and were unable to do that, so we were wondering whether
the issue stems from your environment or software versions (e.g. haiku).
Could you please check and share the packages/versions that are in your
conda environment? Also, does TCRmodel2 give that error for any input, or
does TCRmodel2 give that error regardless of the input TCR/peptide/MHC
sequences? The latter may indicate that the issue is specific to your
environment versus its handling of the input.

Best,
Brian

**Comment by ddiem-ri-4D** [comment] 2024-08-24 04:46
Hi @bpierce12 
Here are the results after I reran with TCR-pMHCI prediction. I'm not sure if the results below are complete; could you please help me check them?

[test_clsI_6kzw.zip](https://github.com/user-attachments/files/16735261/test_clsI_6kzw.zip)

**Comment by bpierce12** [comment] 2024-08-24 11:33
Those results look complete to me, as I see the PDB models and scores. Glad
that it's working for you now! Let me know if you have any other issues in
the future.

**Comment by bpierce12** [comment] 2024-08-24 11:42
Closing because the PDB and scores (statistics.json) files were successfully output for the user. If that error message still occurs during runtime, it does not seem consequential.

**Closed as completed by bpierce12** 2024-08-24 11:42 UTC
